# Generated by Django 4.0.7 on 2022-09-18 11:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_hackernews_fetched_at_alter_hackernews_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackernews',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hackernews',
            name='fetched_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 12, 8, 20, 193707)),
        ),
    ]
