# Generated by Django 4.0.7 on 2022-09-18 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hackernews_host_alter_hackernews_fetched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackernews',
            name='fetched_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 15, 23, 0, 981706)),
        ),
        migrations.AlterField(
            model_name='hackernews',
            name='hackernewsid',
            field=models.BigIntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
