# Generated by Django 4.0.7 on 2022-09-18 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_hackernews_fetched_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackernews',
            name='fetched_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 18, 56, 33, 236139)),
        ),
        migrations.AlterField(
            model_name='hackernews',
            name='hackernewsid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
