# Generated by Django 4.0.7 on 2022-09-17 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackerNews',
            fields=[
                ('hackernewsid', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('by', models.CharField(max_length=300, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('title', models.TextField(null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('urls', models.TextField(blank=True, null=True)),
                ('kids', models.TextField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=datetime.datetime(2022, 9, 17, 9, 19, 14, 137837))),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
