# Generated by Django 4.0.7 on 2022-09-17 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackernews',
            name='fetched_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 10, 8, 29, 988366)),
        ),
        migrations.AlterField(
            model_name='hackernews',
            name='urls',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
